### ISSUE TITLE
[Authentication] - Implement Signup 

### ISSUE THREAD

**Issue by khumodiatla** [DrivenIIDevelop/Digital-Dynasty#10]
Implement the functionalities below 

- [x] **1. The User Database Model**
Description: Define the database model for user accounts to store signup information such as username, email, and hashed password.

- [x] **2. Signup Controller logic**
Description: Implement the controller logic for the signup functionality, including input validation, password hashing, and creating a new user account in the database.

- [x] **3. The Signup endpoint**
Description: Create an API endpoint (/auth/signup/) in the authentication routes to handle user signup requests. This endpoint will receive signup data from clients and invoke the corresponding controller logic to create a new user account.

- [x] **4. Testing - Integration Tests**
Description: Write integration tests to ensure that the signup controller logic is functioning correctly. Test cases should cover various scenarios such as valid input, invalid input, and duplicate usernames or emails.

**Comment by tshegofatsoseane** [comment]
I'm closing this issue since it's merged
