### ISSUE TITLE
[Authentication] - Implement Signin/Login

### ISSUE THREAD

**Issue by khumodiatla** [DrivenIIDevelop/Digital-Dynasty#19]
Implement the functionalities below 

- [x] **1.  Login Controller Logic**
Description: Implement the controller logic for the login functionality, including validating user input, authenticating users, and generating access tokens upon successful login.

- [x] **2.  Login Endpoint**
Description: Create an API endpoint (/auth/login/) in the authentication routes to handle user login requests. This endpoint will receive login credentials from clients and invoke the corresponding controller logic to log in users.

- [x] **3. Token Generation**
Description: Implement a mechanism to generate JWT (JSON Web Token) upon successful authentication. Include necessary user information (e.g., user ID, username) in the token payload for future authorization.

- [x] **4. Testing - Integration Tests**
Description: Write integration tests to verify the correctness of the login controller logic. Test cases should cover scenarios such as valid login credentials, invalid credentials, and unauthorized access attempts.

**Comment by tshegofatsoseane** [comment]
I'm closing this issue since it's merged.
