### ISSUE TITLE
init: API Design

### ISSUE THREAD

**Issue by Piyush-linux** [DrivenIIDevelop/Digital-Dynasty#3]
:heart:  Submit your API design in wiki tabs plz ! ! !

**Comment by tshegofatsoseane** [comment]
Please assign me this issue

**Comment by tshegofatsoseane** [comment]
> ❤️ Submit your API design in wiki tabs plz ! ! !

Please check the wiki tabs, the API design page is there.

**Comment by Piyush-linux** [comment]
@tshegofatsoseane , Would plz also share data modelling schema diagram link .

**Comment by tshegofatsoseane** [comment]
@khumodiatla You mean the "message" key inside the response?

**Comment by khumodiatla** [comment]
@tshegofatsoseane Yes

**Comment by tshegofatsoseane** [comment]
@khumodiatla  What RESTful response format do you prefer?

**Comment by khumodiatla** [comment]
@tshegofatsoseane I don't have a format I prefer. If we need  to send the message we can send a message via `res.json({message: "..."});` or `res.send(message: "..."}); `  in the controllers so no need for it to be in the response. 

It's brings some inconsistency in our responses. Some responses don't have them.

**Comment by tshegofatsoseane** [comment]
Noted, I'll fix that.

**Comment by tshegofatsoseane** [comment]
@khumodiatla Please check it again, and send your feedback.

**Comment by khumodiatla** [comment]
@tshegofatsoseane  Awe, looks good. 
We might make some adjustments if we think of anything to add or remove.

**Comment by khumodiatla** [comment]
Which Issue between between Create Db Schema and  API Design can I grab and implement the code for ?
Or you will do both ?

**Comment by tshegofatsoseane** [comment]
@khumodiatla , I think we should have a meet first to discuss tasks, and start delegating. I don't know, what do you think?

**Comment by Piyush-linux** [comment]
Yes, agreed

**Comment by khumodiatla** [comment]
@tshegofatsoseane Yeah. Agreed

**Comment by tshegofatsoseane** [comment]
I'm closing this issue since we've agreed on the API schema
