### ISSUE TITLE
Schema: Create Database Schema

### ISSUE THREAD

**Issue by tshegofatsoseane** [DrivenIIDevelop/Digital-Dynasty#4]
**Description:**
We need to design and implement a database schema for our accounting software to efficiently store and manage data related to users, invoices, expenses, payments, clients, and vendors. This schema will form the foundation of our application and ensure optimal data organization, retrieval, and manipulation.

**Key Requirements:**
- Define tables for users, invoices, expenses, payments, clients, and vendors.
- Establish appropriate relationships between tables using foreign keys.
- Ensure the use of Snowflake identifiers for primary keys.
- Include necessary fields for each table, such as user details, invoice amounts, payment methods, etc.
- Provide comments to explain the purpose and relationships of each table and field.

**Comment by tshegofatsoseane** [comment]
Here is the database schema

https://dbdiagram.io/d/6615032603593b6b618c8d02

**Comment by Piyush-linux** [comment]
### User Schema thread !
Yo @tshegofatsoseane 
- do we really need state and city ?

**Comment by tshegofatsoseane** [comment]
@Piyush-linux I added them as extra fields to be discussed, but I guess we won't need them then.

**Comment by tshegofatsoseane** [comment]
I'm closing this issue.
